- name: restart_apache
  service: name=apache2 state=restarted enabled=yes
  tags: apache

- name: allow_http
  ufw:
    rule: allow
    port: '80'
  tags: apache

- name: allow_https
  ufw:
    rule: allow
    port: '443'
  tags: apache
